import type { Metadata } from "next";
import "./globals.scss";

import { Layout } from "antd";
import "@ant-design/v5-patch-for-react-19";
import { Content } from "antd/es/layout/layout";
import { Header } from "@/components/Header/header";

export const metadata: Metadata = {
    title: "Next & Python",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Layout>
                    <Header />
                    <Content className="content">
                        <div className="main">{children}</div>
                    </Content>
                </Layout>
            </body>
        </html>
    );
}
